Traceback (most recent call last):
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/petercharlton/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/petercharlton/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
temp_fs = 125
alg = 'd2max'
ibis = pulse_detect(ppg_filt, temp_fs, 5, alg)

print(f"Detected {len(ibis)} beats in the PPG signal using the {alg} algorithm")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-e3b3392caa0a>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mtemp_fs[0m [0;34m=[0m [0;36m125[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0malg[0m [0;34m=[0m [0;34m'd2max'[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mibis[0m [0;34m=[0m [0mpulse_detect[0m[0;34m([0m[0mppg_filt[0m[0;34m,[0m [0mtemp_fs[0m[0;34m,[0m [0;36m5[0m[0;34m,[0m [0malg[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m [0;34m[0m[0m
[1;32m      5[0m [0mprint[0m[0;34m([0m[0;34mf"Detected {len(ibis)} beats in the PPG signal using the {alg} algorithm"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'pulse_detect' is not defined
NameError: name 'pulse_detect' is not defined

